export const accessToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJpYXQiOjE3MDQ2NDgwNTgsImV4cCI6MTcwNTI1Mjg1OCwiYXVkIjoidXNlcnMiLCJpc3MiOiJsb2dpbiIsInN1YiI6IjIifQ.rL_bwT1dgDOpTRMqJgq_m5tk4AuVfXuDXDy3I7xSJWM"

